[package]
name = "satnogs-network-client"
version = "0.2.0"
authors = ["Sebastian Woetzel <wose@zuendmasse.de>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.11", features = ["serde", "rustc-serialize"] }
restson = "0.6.0"
serde = "1.0.111"
serde_derive = "1.0.111"
